name: swine_flu_tracker_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scipy
  - biopython=1.83
  - mafft
  - fasttree
  - blast
  - pip:
    - nextstrain-augur
    - dendropy
    - smof
    - boto3
    - flutile